# this file is a helper to run Acme locally
# starts a mysql instance on port 5450 to use as a local db
version: "3.6"
services:
  mysql-db:
    image: mysql:8.0.31
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: acme
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 20
  mysql_is_ready:
    image: mysql
    depends_on:
      mysql-db:
        condition: service_healthy
volumes:
  db_data:
